### PR TITLE
Polishing test cases for returning null value

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've improved precondition of test cases.
Please review.

### CODE REVIEW

**Comment by emacarron** [comment]
Should the .wasNull() be called on a CallableStatement instead of the ResultSet in the methods that take a cs as input?

**Comment by kazuki43zoo** [comment]
Oh, sorry  ..
It's mistake copy & paste.
I will fix at later.

**Comment by kazuki43zoo** [comment]
@emacarron 

I've fixed mistake.
Please review again.

**Comment by emacarron** [comment]
Thank you!

**Pull request merged**
